[package]
edition = "2021"
name = "rust"
version = "0.1.0"

[workspace]

members = [
  "guessing_game",
  "common_concepts",
  "ownership",
  "ownership_slice",
  "structure",
  "rectangles",
  "enums",
  "if_let",
  "crates",
  "restaurant", "collections",
]

[dependencies]
